export function getColorCode(color) {
  const rawMap = {
    "Academy": "ACADEMY",
    "Acid Orange Melange": "ACIDORNGMLNG",
    "Action": "ACTION",
    "Action Green": "ACTIONGRN",
    "Advantage": "ADVTG",
    "Aegean": "AEGN",
    "Aegean Blue": "AEGNBLUE",
    "Aegean Blue Heather": "AEGNBLUEHTHR",
    "Alloy": "ALLOY",
    "Allure Heather": "ALLUREHTHR",
    "Alpine Navy": "ALPINENV",
    "Aluminum": "ALUM",
    "Anchor": "ANCHOR",
    "Anchor Grey": "ANCHORGRY",
    "Anchor Grey Geo Diamond": "ANCHORGRYGEODIAMOND",
    "Anthracite": "ANTH",
    "Anthracite Heather": "ANTHHTHR",
    "Anthracite Heather/Black": "ANTHHTHR/BLK",
    "Anthracite/Anthracite": "ANTH/ANTH",
    "Anthracite/Black": "ANTH/BLK",
    "Anthracite/White": "ANTH/WHT",
    "Apple": "APPLE",
    "Apple Green": "APPLEGRN",
    "Aqua Blue": "AQUABLUE",
    "Aqua Plaid": "AQUAPLAID",
    "Aquatic Blue": "AQUATICBLUE",
    "Arctic": "ARCTIC",
    "Arctic Pink": "ARCTICPINK",
    "Ash": "ASH",
    "Asphalt": "ASPT",
    "Athletic": "ATH",
    "Athletic Grey Heather/Dark Grey": "ATHGRYHTHR/DRKGRY",
    "Athletic Heather": "ATHHTHR",
    "Atlas": "ATLAS",
    "Atlas Heather": "ATLASHTHR",
    "Atlas/Navy Blue": "ATLAS/NVBLUE",
    "Atomic": "ATOMIC",
    "Azure": "AZURE",
    "Azurite": "AZURITE",
    "Baby": "BABY",
    "Baby Blue": "BABYBLUE",
    "Baby Pink": "BABYPINK",
    "Ballerina": "BLRNA",
    "Bamboo": "BAMBOO",
    "Battleship": "BTLSHP",
    "Battleship Grey": "BTLSHPGRY",
    "Bermuda": "BRMD",
    "Berry": "BERRY",
    "Berry Burst": "BERRYBURST",
    "Beryl Green Heather": "BERYLGRNHTHR",
    "Birch": "BIRCH",
    "Black": "BLK",
    "Black Blue Plaid": "BLKBLUEPLAID",
    "Black Camo": "BLKCAMO",
    "Black Dotted Plaid": "BLKDOTTEDPLAID",
    "Black Frost": "BLKFROST",
    "Black Heather": "BLKHTHR",
    "Black Heather/Black": "BLKHTHR/BLK",
    "Black Heather/White/Black Heather": "BLKHTHR/WHT/BLKHTHR",
    "Black Lime Green": "BLKLIMEGRN",
    "Black Lining Plaid": "BLKLININGPLAID",
    "Black Melange": "BLKMLNG",
    "Black Plaid": "BLKPLAID",
    "Black Powder": "BLKPOWDER",
    "Black Smoke Heather": "BLKSMKHTHR",
    "Black Triad Solid": "BLKTRIADSOLID",
    "Black with Black": "BLK/BLK",
    "Black with Royal Blue": "BLK/RYLBLUE",
    "Black/Anthracite": "BLK/ANTH",
    "Black/Anthracite/White": "BLK/ANTH/WHT",
    "Black/Ash": "BLK/ASH",
    "Black/Ash Gray": "BLK/ASHGRY",
    "Black/Black": "BLK/BLK",
    "Black/Blue": "BLK/BLUE",
    "Black/Charcoal": "BLK/CHR",
    "Black/Charcocal": "BLK/CHR",
    "Black/Chrome": "BLK/CHROME",
    "Black/Cool Grey": "BLK/COOLGRY",
    "Black/Dark Grey": "BLK/DRKGRY",
    "Black/Dark Grey Heather": "BLK/DRKGRYHTHR",
    "Black/Dark Grey/Gym Red": "BLK/DRKGRY/GYMRED",
    "Black/Dark Grey/White": "BLK/DRKGRY/WHT",
    "Black/Game Royal": "BLK/GAMERYL",
    "Black/Graphite": "BLK/GRPH",
    "Black/Grey Steel": "BLK/GRYSTL",
    "Black/Grey Three": "BLK/GRYTHREE",
    "Black/Gym Red": "BLK/GYMRED",
    "Black/Iron Grey": "BLK/IRONGRY",
    "Black/Light Charcoal": "BLK/LTCHR",
    "Black/Light Stone": "BLK/LTSTN",
    "Black/Melange Black": "BLK/MLNGBLK",
    "Black/Petrol": "BLK/PETROL",
    "Black/Red": "BLK/RED",
    "Black/Royal Blue": "BLK/RYLBLUE",
    "Black/Silver": "BLK/SLVR",
    "Black/Varsity Red": "BLK/VARSITYRED",
    "Black/Volt": "BLK/VOLT",
    "Black/White": "BLK/WHT",
    "Black/White/Black": "BLK/WHT/BLK",
    "Black/White/Grey Three": "BLK/WHT/GRYTHREE",
    "Black/Wht": "BLK/WHT",
    "Black/Wolf Grey": "BLK/WOLFGRY",
    "Blackberry": "BLKBERRY",
    "Blackout": "BLKOUT",
    "Blacktop": "BLKTOP",
    "Blazer": "BLAZER",
    "Blended": "BLND",
    "Blossom": "BLOS",
    "Blue": "BLUE",
    "Blue Black Plaid": "BLUEBLKPLAID",
    "Blue Frost": "BLUEFROST",
    "Blue Fusion": "BLUEFUSION",
    "Blue Green: Herb Garden w/ Basil Seeds": "BLUEGREEN",
    "Blue Heather": "BLUEHTHR",
    "Blue Lake": "BLUELAKE",
    "Blue Mist": "BLUEMIST",
    "Blue Navy": "BLUENV",
    "Blue Nebula/Gym Blue": "BLUENEBULA/GYMBLUE",
    "Blue Nights": "BLUENIGHTS",
    "Blue Nights Heather": "BLUENIGHTSHTHR",
    "Blue Note": "BLUENOTE",
    "Blue Plaid": "BLUEPLAID",
    "Blue Quartz": "BLUEQUARTZ",
    "Blue Sapphire": "BLUESAPPHIRE",
    "Blue Sapphire/Black": "BLUESAPPHIRE/BLK",
    "Blue Sapphire/White": "BLUESAPPHIRE/WHT",
    "Blue Space Dye": "BLUESPACEDYE",
    "Blue Stripe": "BLUESTRP",
    "Blue Tint": "BLUETINT",
    "Blue Twill": "BLUETWILL",
    "Blue Void": "BLUEVOID",
    "Blue/Gray": "BLUE/GRY",
    "Blue/Navy": "BLUE/NV",
    "Blue/Silver": "BLUE/SLVR",
    "Blueberry": "BLUEBERRY",
    "Bluff": "BLUFF",
    "Blustery": "BLUSTERY",
    "Blustery/Navy": "BLUSTERY/NV",
    "Bone": "BONE",
    "Bourdeaux": "BOURDEAUX",
    "Breaker Blue": "BREAKERBLUE",
    "Break-Up": "BU",
    "BreakupCountry": "BUC",
    "Bright": "BRIGHT",
    "Bright Lavender": "BRIGHTLAV",
    "Bright Spruce Heather": "BRIGHTSPRUCEHTHR",
    "Bright White": "BRIGHTWHT",
    "Brilliant": "BRLT",
    "Brilliant Blue": "BRLTBLUE",
    "Brilliant Blue Heather": "BRLTBLUEHTHR",
    "Brilliant Orange": "BRLTORNG",
    "Brisk": "BRISK",
    "Brisk Blue": "BRISKBLUE",
    "Brite Lime": "BRITELIME",
    "Brite Orange": "BRITEORNG",
    "Bronze": "BRONZE",
    "Bronze Metallic": "BRONZEMTLC",
    "Brown": "BROWN",
    "Brush": "BRUSH",
    "Bungalow": "BUNG",
    "Burgundy": "BURGUNDY",
    "Burnt": "BURNT",
    "Burnt Olive": "BURNTOLIVE",
    "Burnt Olive Green": "BURNTOLIVEGRN",
    "Camo": "CAMO",
    "Camo/Black": "CAMO/BLK",
    "Camoflauge": "CAMO",
    "Candy": "CANDY",
    "Candy Pink": "CANDYPINK",
    "Carbon": "CARBON",
    "Carbon Heather": "CARBONHTHR",
    "Cardinal": "CARDINAL",
    "Cardinal Heather": "CARDINALHTHR",
    "Carhartt": "CT",
    "Carhartt Brown": "CTBROWN",
    "Caribbean": "CARIB",
    "Carolina": "CRLNA",
    "Carolina Blue": "CRLNABLUE",
    "Carolina Blue/White": "CRLNABLUE/WHT",
    "Carrot": "CARROT",
    "Cascade": "CASCADE",
    "Cascade Metallic": "CASCADEMTLC",
    "Caviar": "CAVIAR",
    "Caviar Black": "CAVIARBLK",
    "Cement": "CMNT",
    "Chalk": "CHALK",
    "Chambray Blue": "CHAMBRAYBLUE",
    "Charcoal": "CHR",
    "Charcoal Grey": "CHRGRY",
    "Charcoal Grey Heather": "CHRGRYHTHR",
    "Charcoal Heather": "CHRHTHR",
    "Charcoal Plaid": "CHRPLAID",
    "Charcoal/Black": "CHR/BLK",
    "Charcoal/Charcoal": "CHR/CHR",
    "Charcoal/Navy": "CHR/NV",
    "Charcoal/White": "CHR/WHT",
    "Charter": "CHARTER",
    "Charter Blue": "CHARTERBLUE",
    "Charter Blue Heather": "CHARTERBLUEHTHR",
    "Chartreuse": "CHARTREUSE",
    "Chartreuse/Dark Grey": "CHARTREUSE/DRKGRY",
    "Chill": "CHILL",
    "Chlorophyll": "CHLOROPHYLL",
    "Chocolate": "CHOC",
    "Chrome": "CHROME",
    "Cinder": "CINDER",
    "Cinder Gray": "CINDERGRY",
    "Classic": "CLSC",
    "Classic Blue": "CLSCBLUE",
    "Classic Blue Heather": "CLSCBLUEHTHR",
    "Classic Navy": "CLSCNV",
    "Clay": "CLAY",
    "Clay Green": "CLAYGRN",
    "Clear": "CLEAR",
    "Clear/Black": "CLEAR/BLK",
    "Cloud Heather": "CLOUDHTHR",
    "Coal": "COAL",
    "Coal Heather": "COALHTHR",
    "Coastal": "CSTL",
    "Coastal Fjord": "CSTLFJORD",
    "Cobalt": "CBLT",
    "Cobalt Blue": "CBLTBLUE",
    "College": "COLLEGE",
    "College Navy": "COLLEGENV",
    "College Orange": "COLLEGEORNG",
    "College Orange/Navy Blue": "COLLEGEORNG/NVBLUE",
    "Collegiate": "CLGT",
    "Collegiate Navy": "CLGTNV",
    "Collegiate Navy Melange": "CLGTNVMLNG",
    "Collegiate Navy/White": "CLGTNV/WHT",
    "Collegiate Royal": "CLGTRYL",
    "Collegiate Royal Heather/Carbon": "CLGTRYLHTHR/CARBON",
    "Columbia": "CLMB",
    "Columbia Blue/White/Navy": "CLMBBLUE/WHT/NV",
    "Concrete": "CONCRETE",
    "Constellation": "CONSTELLATION",
    "Continental": "CNTL",
    "Cool": "COOL",
    "Cool Grey": "COOLGRY",
    "Cool Grey/Anthracite": "COOLGRY/ANTH",
    "Cool Grey/Dark Grey": "COOLGRY/DRKGRY",
    "Cool Grey/Navy/White": "COOLGRY/NV/WHT",
    "Cool Grey/Photo Blue": "COOLGRY/PHOTBLUE",
    "Cool Grey/White": "COOLGRY/WHT",
    "Copper": "COPPER",
    "Copper Finish": "COPPER",
    "Coral": "CORAL",
    "Cork": "CORK",
    "Cornsilk": "CORNSILK",
    "Country": "CTRY",
    "Court": "COURT",
    "Court Blue": "COURTBLUE",
    "Court Purple": "COURTPRP",
    "Coyote": "COYOTE",
    "Coyote Brown": "COYOTEBROWN",
    "Cream": "CREAM",
    "Crimson": "CRMN",
    "Crimson Red": "CRMNRED",
    "Cyan Blue": "CYANBLUE",
    "Dark": "DRK",
    "Dark Black Heather": "DRKBLKHTHR",
    "Dark Blue": "DRKBLUE",
    "Dark Blue with White Rope": "DRKBLUE/WHT",
    "Dark Brown": "DRKBROWN",
    "Dark Brush": "DRKBRUSH",
    "Dark Charcoal": "DRKCHR",
    "Dark Charcoal Heather": "DRKCHRHTHR",
    "Dark Gray": "DRKGRY",
    "Dark Gray Heather": "DRKGRYHTHR",
    "Dark Green": "DRKGRN",
    "Dark Grey": "DRKGRY",
    "Dark Grey & Cool Grey": "DRKGRY/COOLGRY",
    "Dark Grey Heather": "DRKGRYHTHR",
    "Dark Grey Heather/Dark Grey Heather": "DRKGRYHTHR/DRKGRYHTHR",
    "Dark Grey/Black": "DRKGRY/BLK",
    "Dark Grey/Black/Sport Fuchsia": "DRKGRY/BLK/SPTFCHA",
    "Dark Grey/Cool Grey": "DRKGRY/COOLGRY",
    "Dark Grey/Cool Grey/Volt": "DRKGRY/COOLGRY/VOLT",
    "Dark Grey/Sport Fuchsia": "DRKGRY/SPTFCHA",
    "Dark Grey/White": "DRKGRY/WHT",
    "Dark Heather Gray": "DRKHTHRGRY",
    "Dark Heather Grey": "DRKHTHRGRY",
    "Dark Khaki": "DRKKHAKI",
    "Dark Maroon": "DRKMRN",
    "Dark Navy": "DRKNV",
    "Dark Obsidian": "DRKOBSIDIAN",
    "Dark Shadow Grey Heather": "DRKSDWGRYHTHR",
    "Dark Smoke Grey": "DRKSMKGRY",
    "Dark Smoke Heather": "DRKSMKHTHR",
    "Dark Teal": "DRKTEAL",
    "Dark Teal Heather": "DKTEALHTHR",
    "Dawn Blue": "DAWNBLUE",
    "Deep": "DP",
    "Deep Bay": "DPBAY",
    "Deep Berry": "DPBERRY",
    "Deep Black": "DPBLK",
    "Deep Blue": "DPBLUE",
    "Deep Harbor/RTIC Ice": "DPHARBOR/RTICICE",
    "Deep Maroon": "DPMRN",
    "Deep Navy": "DPNV",
    "Deep Navy/White": "DPNV/WHT",
    "Deep Ocean": "DPOCEAN",
    "Deep Royal": "DPRYL",
    "Deep Royal Blue": "DPRYLBLUE",
    "Deep Royal Blue/Black": "DPRYLBLUE/BLK",
    "Deep Smoke": "DPSMK",
    "Deep Smoke Heather": "DPSMKHTHR",
    "Denim": "DENIM",
    "Denim Blue": "DENIMBLUE",
    "Denim Navy": "DENIMNV",
    "Desert": "DESERT",
    "Desert Khaki": "DESERTKHAKI",
    "Desert Orange": "DESERTORNG",
    "Desert/White": "DESERT/WHT",
    "Diamond": "DIAM",
    "Diesel": "DSL",
    "Diesel Grey": "DSLGRY",
    "Digital": "DIGITAL",
    "Dirty Wash Denim": "DIRTYWASHDENIM",
    "Distressed": "DSTRD",
    "Distressed Brown": "DSTRDBROWN",
    "DNA": "DNA",
    "Dress": "DRESS",
    "Dress Blue Navy": "DRESSBLUENV",
    "Driftwood": "DRIFTWOOD",
    "Dune": "DUNE",
    "Dusk Blue": "DUSKBLUE",
    "Dusty": "DST",
    "Dusty Blue": "DUSTYBLUE",
    "Dusty Rose": "DSTYROSE",
    "Dye": "DYE",
    "Earthy": "EARTHY",
    "Earthy Green": "EARTHYGRN",
    "Echo Steel": "ECHOSTL",
    "Electric": "ELTRC",
    "Electric Blue": "ELTRCBLUE",
    "Electric Blue/Black": "ELTRCBLUE/BLK",
    "Elemental": "ELMNTL",
    "Elemental Gray": "ELEMENTALGRY",
    "Elemental Grey": "ELMNTLGRY",
    "Elemental Grey Heather": "ELEMENTALGRYHTHR",
    "Elements": "ELEMENTS",
    "End": "END",
    "English Plaid": "ENGPLAID",
    "Espresso": "ESPRESSO",
    "Expedition": "EXP",
    "Federal Blue": "FEDERALBLUE",
    "Field Khaki": "FIELDKHAKI",
    "Fire": "FIRE",
    "Fireberry": "FIREBERRY",
    "Fireberry/Sport Fuchsia": "FIREBERRY/SPTFCHA",
    "Five": "FIVE",
    "Flag Red": "FLAGRED",
    "Flame Red/White": "FLAMERED/WHT",
    "Flamingo": "FLAMINGO",
    "Flint": "FLINT",
    "Flint Grey": "FLINTGRY",
    "Fluorescent": "FLRSCNT",
    "Flush": "FLUSH",
    "Flush Pink": "FLUSHPINK",
    "Focus Blue Melange": "FOCUSBLUEMLNG",
    "Fog": "FOG",
    "Force Blue": "FORCEBLUE",
    "Force Blue Heather": "FORCEBLUEHTHR",
    "Forest": "FOREST",
    "Forest Green": "FORESTGRN",
    "Forest Green Heather": "FORESTGRNHTHR",
    "Fossil": "FOSSIL",
    "Fox": "FOX",
    "FR Khaki": "KHAKI",
    "FR Medium Gray": "MGRY",
    "French": "FRENCH",
    "French Blue": "FRENCHBLUE",
    "Frontier": "FRONTIER",
    "Frontier/Black/Black": "FRONTIER/BLK/BLK",
    "Frost": "FROST",
    "Fuchsia": "FCHA",
    "Fuschia": "FCHA",
    "Game": "GAME",
    "Game Royal": "GAMERYL",
    "Game Royal Heather": "GAMERYLHTHR",
    "Game Royal/Black": "GAMERYL/BLK",
    "Game Royal/Black/White": "GAMERYL/BLK/WHT",
    "Game Royal/Dark Grey Heather": "GAMERYL/DRKGRYHTHR",
    "Game Royal/Midnight Navy": "GAMERYL/MDNTNV",
    "Game Royal/White": "GAMERYL/WHT",
    "Gate": "GATE",
    "Gear Grey": "GEARGRY",
    "Gear Grey Heather": "GEARGRYHTHR",
    "Glacier": "GLACIER",
    "Glory": "GLORY",
    "Glory Blue": "GLORYBLUE",
    "Glow Blue/White": "GLOWBLUE/WHT",
    "Glow Blue/White/Navy": "GLOWBLUE/WHT/NV",
    "Gold": "GOLD",
    "Gold/Black": "GOLD/BLK",
    "Gold/Green": "GOLD/GRN",
    "Gold/Silver": "GOLD/SLVR",
    "Gorge": "GORGE",
    "Gorge Green": "GORGEGRN",
    "Granite": "GRANITE",
    "Granite Grey": "GRANITEGRY",
    "Granite Heather": "GRANITEHTHR",
    "Graphite": "GRPH",
    "Graphite Heather": "GRPHHTHR",
    "Graphite Melange/Graphite": "GRPHMLNG/GRPH",
    "Graphite/Black": "GRPH/BLK",
    "Graphite/Cyper Green": "GRPH/CYBERGRN",
    "Gravel": "GRAVEL",
    "Gray": "GRY",
    "Gray with Black": "GRY/BLK",
    "Gray/Black": "GRY/BLK",
    "Green": "GRN",
    "Green Oxide Melange": "GRNOXIDEMLNG",
    "Grey": "GRY",
    "Grey Five/Black": "GRYFIVE/BLK",
    "Grey Five/Grey Three": "GRYFIVE/GRYTHREE",
    "Grey Frost": "GRYFROST",
    "Grey Heather": "GRYHTHR",
    "Grey Heather/Black/Grey Heather": "GRYHTHR/BLK/GRYHTHR",
    "Grey Heather/White/Grey Heather": "GRYHTHR/WHT/GRYHTHR",
    "Grey Plaid": "GRYPLAID",
    "Grey Smoke": "GRYSMK",
    "Grey Steel": "GRYSTL",
    "Grey Steel Heather": "GRYSTLHTHR",
    "Grey Steel/Bone": "GRYSTL/BONE",
    "Grey Steel/Purple": "GRYSTL/PRP",
    "Grey Three": "GRYTHREE",
    "Grey Three Heather/Carbon": "GRYTHREEHTHR/CARBON",
    "Grey Three Melange": "GRYTHREEMLNG",
    "Grey Three/Black": "GRYTHREE/BLK",
    "Grey Three/Team Royal/Navy": "GRYTHREE/TEAMRYL/NV",
    "Grey/Charcoal/Navy": "GRY/CHR/NV",
    "Greystone": "GRYSTONE",
    "Grid": "GRID",
    "Grid Iron": "GRIDIRON",
    "Gridiron": "GRIDIRON",
    "Gulf Stream": "GULFSTREAM",
    "Gunmetal": "GUNMTL",
    "Gunmetal Heather": "GUNMTLHTHR",
    "Gusty": "GUSTY",
    "Gusty Grey": "GUSTYGRY",
    "Gusty Grey Heather": "GUSTYGRYHTHR",
    "Gym": "GYM",
    "Gym Blue": "GYMBLUE",
    "Gym Blue/Black": "GYMBLUE/BLK",
    "Gym Blue/Gym Blue": "GYMBLUE/GYMBLUE",
    "Gym Blue/White": "GYMBLUE/WHT",
    "Gym Red": "GYMRED",
    "Gym Red/Black": "GYMRED/BLK",
    "Gym Red/Dark Grey Heather": "GYMRED/DRKGRYHTHR",
    "Gym Red/Team Red": "GYMRED/TEAMRED",
    "Harbor Mist": "HARBORMIST",
    "Havasu": "HAVASU",
    "Hazy Blue": "HAZYBLUE",
    "Heather": "HTHR",
    "Heather Black": "HTHRBLK",
    "Heather Brown": "HTHRBROWN",
    "Heather Dark Charcoal": "HTHRDRKCHR",
    "Heather Gray/Black/White": "HTHRGRY/BLK/WHT",
    "Heather Grey": "HTHRGRY",
    "Heather Grey/Beige/Ocean Blue": "HTHRGRY/BEIGE/OCEAN",
    "Heather Grey/Black": "HTHRGRY/BLK",
    "Heather Grey/Flag": "HTHRGRY/FLAG",
    "Heather Grey/Navy": "HTHRGRY/NV",
    "Heather Grey/Royal": "HTHRGRY/RYL",
    "Heather Grey/Stars Stripes": "HTHRGRY/FLAG",
    "Heather Grey/White": "HTHRGRY/WHT",
    "Heather Grey/White/Heather Grey": "HTHRGRY/WHT/HTHRGRY",
    "Heather Khaki": "HTHRKHAKI",
    "Heather Navy": "HTHRNV",
    "Heather Red": "HTHRRED",
    "Heather Royal": "HTHRRYL",
    "Heather Stone": "HTHRSTN",
    "Heathered": "HTHRD",
    "Heathered Charcoal": "HTHRDCHR",
    "Heathered Grey": "HTHRDGRY",
    "Heritage Blue": "HERITAGEBLUE",
    "High Rise": "HIGHRISE",
    "High Tide": "HIGHTIDE",
    "Highlander": "HLNDR",
    "HiVis": "HIVIS",
    "Hot": "HOT",
    "Hot Pink": "HOTPINK",
    "HR New Hire Kit": "NEW_HIRE_KIT",
    "Hunter": "HUNTER",
    "Hunter Green": "HUNTERGRN",
    "Hyper Magenta": "HYPERMAGENTA",
    "Ice": "ICE",
    "Ice White": "ICEWHT",
    "Indigo": "INDIGO",
    "Indigo Blue": "INDIGOBLUE",
    "Indigo Wash": "INDIGOWASH",
    "Insignia Blue": "INSIGNIABLUE",
    "Iron": "IRON",
    "Iron Gate": "IRONGATE",
    "Iron Gray": "IRONGRY",
    "Iron Grey": "IRONGRY",
    "Ivory": "IVR",
    "Ivory Chiffon": "IVRCHIFFON",
    "Ivory Snow": "IVRSNOW",
    "Jade": "JADE",
    "Jake Blue": "JAKEBLUE",
    "Jet Black": "JETBLK",
    "Jet Gray": "JETGRY",
    "Jet Gray/Black": "JETGRY/BLK",
    "Jet Gray/Blue": "JETGRY/BLUE",
    "Jet/Black": "JET/BLK",
    "Kelly": "KELLY",
    "Kelly Green": "KELLYGRN",
    "Kentucky Blue Heather": "KENTUCKYBLUEHTHR",
    "Khaki": "KHAKI",
    "Khaki Green/Brown": "KHAKIGRN/BROWN",
    "Khaki Heather": "KHAKIHTHR",
    "Khaki/White": "KHAKI/WHT",
    "Kryptek": "KRP",
    "Lake Blue": "LAKEBLUE",
    "Large": "L",
    "Large - Tall": "LT",
    "Large/XLarge": "L/XL",
    "Laser Red/Heather Grey": "LASERRED/HTHRGRY",
    "Lavender": "LAV",
    "Lawn": "LAWN",
    "Legend": "LEGD",
    "Leopard": "LEOPARD",
    "Liberty Navy": "LIBERTYNV",
    "Liberty Navy Heather": "LIBERTYNVHTHR",
    "Lichen": "LICHEN",
    "Light": "LT",
    "Light Blue": "LTBLUE",
    "Light Blue Plaid": "LTBLUEPLAID",
    "Light Brown": "LTBROWN",
    "Light Brown/Silver": "LTBROWN/SLVR",
    "Light Game Royal Heather": "LTGAMERYLHTHR",
    "Light Gray": "LTGRY",
    "Light Grey": "LTGRY",
    "Light Grey Heather": "LTGRYHTHR",
    "Light Heather Gray": "LTHTHRGRY",
    "Light Heather Grey": "LTHTHRGRY",
    "Light Photo Blue": "LTPHOTOBLUE",
    "Light Photo Blue/Deep Royal": "LTPHOTOBLUE/DPRYL",
    "Light Pink": "LTPINK",
    "Light Shadow Grey Heather": "LTSDWGRYHTHR",
    "Light Stonewash": "LTSTNWASH",
    "Lilac": "LILAC",
    "Lime": "LIME",
    "Lime Green": "LIMEGRN",
    "Lime Shock": "LIMESHOCK",
    "Loden Heather": "LODENHTHR",
    "LT-3XLT": "LT,XLT,2XLT,3XLT",
    "LT-4XLT": "LT,XLT,2XLT,3XLT,4XLT",
    "Lucid": "LUCID",
    "Lucid Green": "LUCIDGRN",
    "Lucky": "LUCKY",
    "Lucky Green": "LUCKYGRN",
    "Lucky Green/Black": "LUCKYGRN/BLK",
    "Lucky Green/White": "LUCKYGRN/WHT",
    "M/L": "M/L",
    "Magenta Heather": "MAGENTAHTHR",
    "Magnet": "MAGNET",
    "Maize": "MAIZE",
    "Marina": "MARINA",
    "Marine": "MARINE",
    "Marolina Blue": "MAROLINABLUE",
    "Maroon": "MRN",
    "Marsh Duck Camo/Army Olive": "MDC/ARMYOLIVE",
    "Marshmallow": "MMLW",
    "Marshmallow/Awareness Pink/Gusty Grey": "MMW/AWPINK/GUSTYGRY",
    "Martime Blue": "MARTIMEBLUE",
    "Matte": "MATTE",
    "Matte Black": "MATTEBLK",
    "Matte Constellation": "MATTECONST",
    "Matte Navy": "MATTENV",
    "Mauve": "MAUVE",
    "Mauvelous": "MAUVELOUS",
    "Mean": "MEAN",
    "Mean Green": "MEANGRN",
    "Mediterranean": "MDTR",
    "Medium": "M",
    "Medium - Tall": "MT",
    "Medium Blue": "MBLUE",
    "Medium Grey": "MGRY",
    "Medium/Large": "M/L",
    "Melange": "MLNG",
    "Metal": "MTL",
    "Metal Blue Heather": "MTLBLUEHTHR",
    "Metallic": "MTLC",
    "Metallic Blue": "MTLCBLUE",
    "Microchip Grey": "MICROCHIPGRY",
    "Mid": "MID",
    "Mid Grey Dark Heather/TNF Black": "MGRYDRKHTHR/TNFBLK",
    "Mid Grey/Asphalt Grey": "MIDGRY/ASPTGRY",
    "Midnight": "MDNT",
    "Midnight Black": "MDNTBLK",
    "Midnight Blue Shimmer": "MDNTBLUESHIMMER",
    "Midnight Heather": "MDNTHTHR",
    "Midnight Navy": "MDNTNV",
    "Midnight Navy Heather/Midnight Navy": "MDNTNVHTHR/MDNTNV",
    "Midnight Navy/Dark Obsidian": "MDNTNV/DRKOBSIDIAN",
    "Midnight Navy/Midnight Navy": "MDNTNV/MDNTNV",
    "Midnight Navy/Photo Blue": "MDNTNV/PHOTBLUE",
    "Military": "MILTRY",
    "Mint": "MINT",
    "Mist": "MIST",
    "Monsoon": "MONSOON",
    "Monsoon Heather": "MONSOONHTHR",
    "Monster": "MNSTR",
    "Monster Blue/Asphalt Grey": "MNSTRBLUE/ASPTGRY",
    "Monument": "MONUMENT",
    "Monument Grey": "MONUMENTGRY",
    "Moonlit Shadow": "MOONLITSDW",
    "Moroccan": "MOROCCAN",
    "Moroccan Blue": "MOROCCANBLUE",
    "Moss Green": "MOSSGRN",
    "Mossy": "MOS",
    "Mossy Oak Break-Up Country/Black": "MOSOAKBUC/BLK",
    "Mossy Oak Country DNA/Black": "MOSOAKCTRYDNA/BLK",
    "Mossy Oak Country DNA/Flag": "MOSOAKCTRYDNA/FLAG",
    "Mossy Oak New Break-Up": "MONBU",
    "Mountain": "MOUNTAIN",
    "Mountain Blue": "MOUNTAINBLUE",
    "Multi Color": "MLTCOLOR",
    "Multicam": "MCAM",
    "Multiple": "MULTICOLOR",
    "M-XL": "M,L,XL",
    "Natural": "NATURAL",
    "Natural Bamboo": "BAMBOO",
    "Natural/Black": "NATURAL/BLK",
    "Natural/Forest": "NATURAL/FOREST",
    "Natural/Navy": "NATURAL/NV",
    "Natural/Red": "NATURAL/RED",
    "Natural/Spruce": "NATURAL/SPRUCE",
    "Naval Academy": "NAVALACADEMY",
    "Navy": "NV",
    "Navy Blazer": "NVBLAZER",
    "Navy Blazer Heather": "NVBLAZERHTHR",
    "Navy Blue": "NVBLUE",
    "Navy Blue with Black accents": "NVBLUE",
    "Navy Blue/Ash Gray": "NVBLUE/ASHGRY",
    "Navy Blue/Grey": "NVBLUE/GRY",
    "Navy Blue/Platinum Gray": "NVBLUE/PLATGRY",
    "Navy Blue/White/Grey Three": "NVBLUE/WHT/GRYTHREE",
    "Navy Geo Diamond": "NVGEODIAMOND",
    "Navy Heather": "NVHTHR",
    "Navy Heather/White/Navy Heather": "NVHTHR/WHT/NVHTHR",
    "Navy Melange": "NVMLNG",
    "Navy/Black": "NV/BLK",
    "Navy/Charcoal": "NV/CHR",
    "Navy/Game Royal": "NV/GAMERYL",
    "Navy/Gym Red": "NV/GYMRED",
    "Navy/Navy": "NV/NV",
    "Navy/White": "NV/WHT",
    "Navy/White/Red": "NV/WHT/RED",
    "NB#6M#12M#18M#24M": "NB,6M,12M,18M,24M",
    "Nebula": "NEBULA",
    "Neon": "NEON",
    "Neon Green": "NEONGRN",
    "Neon Pink": "NEONPINK",
    "Neon Pink ": "NEONPINK",
    "Neon Yellow": "NEONYLW",
    "Neptune": "NEPTUNE",
    "New": "NEW",
    "New Car Dark Blue": "NEWCARDKBLUE",
    "New Navy": "NEWNV",
    "New Royal Heather": "NEWRYLHTHR",
    "Newborn": "NB",
    "Newport": "NEWPORT",
    "Newport Blue": "NEWPORTBLUE",
    "Nickel": "NICKEL",
    "Night": "NIGHT",
    "Night Navy": "NIGHTNV",
    "Night Owl": "NIGHTOWL",
    "Night Sky Blue/Black": "NIGHTSKYBLUE/BLK",
    "Nights": "NIGHTS",
    "Noise": "NOISE",
    "Norse": "NORSE",
    "Norse Blue Space Dye": "NORSEBLUESPACEDYE",
    "Oak": "OAK",
    "Oatmeal": "OATMEAL",
    "Obsidian": "OBSIDIAN",
    "Oceanic": "OCN",
    "Oceanside": "OCEANSIDE",
    "Old": "OLD",
    "Olive": "OLIVE",
    "Olive Green": "OLIVEGRN",
    "One Size Fits Most": "OSFM",
    "Onyx": "ONYX",
    "Opal": "OPAL",
    "Opal White": "OPALWHT",
    "Orange": "ORNG",
    "Orange Chip": "ORNGCHIP",
    "Original": "ORIG",
    "OSFA": "OSFM",
    "OSFM": "OSFM",
    "Oval": "OVAL",
    "Oxford": "OXFD",
    "Oxford Blue": "OXFDBLUE",
    "Oxford Heather": "OXFDHTHR",
    "Oxide": "OXIDE",
    "Oyster": "OYSTER",
    "Pacific": "PACIFIC",
    "Pale": "PALE",
    "Parchment": "PARCHMENT",
    "Parisian Blue": "PARISIANBLUE",
    "Passion Pink Stripe": "PSNPINKSTRP",
    "Patriot": "PATRIOT",
    "Patriot Blue/White": "PATRIOTBLUE/WHT",
    "Peacoat": "PECT",
    "Peacoat Navy": "PEACOATNV",
    "Pearl": "PEARL",
    "Pearl Grey": "PEARLGRY",
    "Pearl Pink": "PEARLPINK",
    "Pebble": "PEBBLE",
    "Pebble Grey": "PEBBLEGRY",
    "Peppermint": "PEPPERMINT",
    "Peri Blue": "PERIBLUE",
    "Petrol": "PTRL",
    "Petrol Grey Heather": "PTRLGRYHTHR",
    "Photo": "PHOTO",
    "Pine": "PINE",
    "Pink": "PINK",
    "Pink Blossom": "PINKBLOS",
    "Platinum": "PLATINUM",
    "Platinum Gray": "PLATINUMGRY",
    "Polar": "POLAR",
    "Polar Heather": "POLARHTHR",
    "Polished": "POLISHED",
    "Polished Heather": "POLISHEDHTHR",
    "Pond Blue Heather": "PONDBLUEHTHR",
    "Pop Raspberry Heather": "POPRSBRYHTHR",
    "Premium": "PRM",
    "Prewash": "PREWASH",
    "Pro": "PRO",
    "Puma Black": "PUMABLK",
    "Pure": "PURE",
    "Purple": "PRP",
    "Purple Mist": "PRPMIST",
    "Quiet": "QUIET",
    "Quiet Shade": "QUIETSHADE",
    "Quiet Shade Grey": "QUIETSHADEGRY",
    "Quiet Shade Grey Heather": "QUIETSHADEGRYHTHR",
    "Quiet Shade Grey/Black": "QUIETSHADEGRY/BLK",
    "Rainstorm": "RNSTM",
    "Raspberry": "RSPBRY",
    "Rawhide": "RAWHIDE",
    "Realtree": "RTREE",
    "Realtree Xtra": "REALTREEXTRA",
    "Realtree Xtra/Black": "RTREEXTRA/BLK",
    "Rectangle": "RECT",
    "Red": "RED",
    "Red Frost": "REDFROST",
    "Red Heather/White/Red Heather": "REDHTHR/WHT/REDHTHR",
    "Red Pepper": "REDPEPPER",
    "Red Plaid": "REDPLAID",
    "Red/Black": "RED/BLK",
    "Red/Light Stone": "RED/LTSTN",
    "Red/White": "RED/WHT",
    "Red/White/Navy": "RED/WHT/NV",
    "Reflective": "RFV",
    "Reflex Blue": "REFLEXBLUE",
    "Regatta": "RGTA",
    "Regatta Blue": "RGTBLUE",
    "Regatta Blue/Navy": "RGTBLUE/NV",
    "Rich": "RICH",
    "Rich Red": "RICHRED",
    "Riptide": "RIPTIDE",
    "River": "RVR",
    "River Blue": "RVRBLUE",
    "River Blue Navy": "RVRBLUENV",
    "River Blue Navy Heather": "RVRBLUENVHTHR",
    "River Blue Navy/Chrome": "RVRBLUENV/CHROME",
    "River Blue Navy/River Blue Navy": "RVRBLUENV/RVRBLUENV",
    "River Blue/Black": "RVRBLUE/BLK",
    "River Green": "RVRGRN",
    "Rogue Grey": "ROGUEGRY",
    "Rope": "ROPE",
    "Rose": "ROSE",
    "Rose Gold": "ROSEGOLD",
    "Rose Quartz": "ROSEQUARTZ",
    "Royal": "RYL",
    "Royal/Classic Navy": "RYL/CLSCNV",
    "Royal Black": "RYLBLK",
    "Royal Blue": "RYLBLUE",
    "Royal Blue/Gray": "RYLBLUE/GRY",
    "Royal Blue/Grey": "RYLBLUE/GRY",
    "Royal Heather/White": "RYLHTHR/WHT",
    "Royal Heather/White/Royal Heather": "RYLHTHR/WHT/RYLHTHR",
    "Royal/Black": "RYL/BLK",
    "Royal/Black Trim": "RYL/BLKTRIM",
    "Royal/Heather Grey/White": "RYL/HTHRGRY/WHT",
    "Royal/HeatherGrey/White": "RYL/HTHRGRY/WHT",
    "Royal/White": "RYL/WHT",
    "Ruby": "RUBY",
    "Rush": "RUSH",
    "Rustic": "RUSTIC",
    "Rustic/Gold": "RUSTIC/GOLD",
    "S#M/L": "S,M/L",
    "S/M#L/XL": "S/M,L/XL",
    "S/M#M/L#L/XL": "S/M,M/L,L/XL",
    "S-2XL": "S,M,L,XL,2XL",
    "S-3XL": "S,M,L,XL,2XL,3XL",
    "S-4XL": "S,M,L,XL,2XL,3XL,4XL",
    "S-5XL": "S,M,L,XL,2XL,3XL,4XL,5XL",
    "S-6XL": "S,M,L,XL,2XL,3XL,4XL,5XL,6XL",
    "Safety": "SFTY",
    "Safety Green": "SFTYGRN",
    "Safety Yellow": "SFTYYLW",
    "Sage": "SAGE",
    "Sail": "SAIL",
    "Salsa": "SALSA",
    "Salsa Red": "SALSARED",
    "Sand": "SAND",
    "Sand Heather": "SANDHTHR",
    "Sanded Denim": "SANDEDDENIM",
    "Sandstone": "SANDSTN",
    "Sangria": "SANGRIA",
    "Sapphire": "SAPPHIRE",
    "Sargasso Sea": "SARGASSOSEA",
    "Saybrook Blue": "SAYBROOKBLUE",
    "Scarlet": "SCARLET",
    "Scarlet Red": "SCARLETRED",
    "Scarlet Red/White": "SCARLETRED/WHT",
    "Sea Blue": "SEABLUE",
    "Seaglass": "SEAGLASS",
    "Shade": "SHADE",
    "Shaded Spruce": "SHADEDSPRUCE",
    "Shadow": "SDW",
    "Shadow Grey": "SDWGRY",
    "Shadow Grey Heather": "SDWGRYHTHR",
    "Shady": "SHADY",
    "Shady Blue": "SHADYBLUE",
    "Shale": "SHALE",
    "Shimmer": "SHIMMER",
    "Shy Marshmallow": "SHYMARSHMALLOW",
    "SIGNAL": "SGL",
    "Silver": "SLVR",
    "Silver Fox": "SLVRFOX",
    "Silver Fox Heather": "SLVRFOXHTHR",
    "Silver Heather": "SLVRHTHR",
    "Silver with Blue Bezel": "SLVR/BLUE",
    "Silver with Green Bezel": "SLVR/GREEN",
    "Silver/Black": "SLVR/BLK",
    "Silver/Light Wood": "SLVR/LTWOOD",
    "Sky": "SKY",
    "Sky Blue": "SKYBLUE",
    "Skyscraper": "SKYSCRAPER",
    "Slate": "SLATE",
    "Slate Blue": "SLATEBLUE",
    "Slate Grey": "SLATEGRY",
    "Small": "S",
    "Small/Medium": "S/M",
    "Smoke": "SMK",
    "Snow": "SNOW",
    "Soft": "SOFT",
    "Soft Mint": "SOFTMINT",
    "Soft Ruby": "SOFTRUBY",
    "Soft Yellow": "SOFTYLW",
    "Solar": "SOLAR",
    "Solid": "SOLID",
    "Solid White": "SLDWHT",
    "Space": "SPACE",
    "Spar Blue": "SPARBLUE",
    "Sport": "SPT",
    "Sport Blue": "SPTBLUE",
    "Sport Dark Navy": "SPTDKNV",
    "Sport Grey": "SPTGRY",
    "Sport Light Blue": "SPTLTBLUE",
    "Sport Silver": "SPTSLVR",
    "Spruce": "SPRUCE",
    "Square": "SQU",
    "Stainless": "STAINLESS",
    "Star": "STR",
    "Starlight": "STARLIGHT",
    "Starphire Crystal": "STARPHIRECRYSTAL",
    "Stars": "STRS",
    "Stars&Stripes": "STRS&STRPS",
    "Steel": "STL",
    "Steel Gray": "STLGRY",
    "Steel Grey": "STLGRY",
    "Steel Grey/Light Stone": "STEELGRY/LTSTN",
    "Sterling": "STRLG",
    "Sterling Grey": "STRLGGRY",
    "Stone": "STONE",
    "Stonewash": "STNWSH",
    "Storm": "STORM",
    "Storm Grey": "STORMGRY",
    "Stripe": "STRP",
    "Stripes": "STRPS",
    "Strong Blue": "STRONGBLUE",
    "Summit": "SUMMIT",
    "Sunset": "SUNSET",
    "S-XL": "S,M,L,XL",
    "Tan": "TAN",
    "Tarmac": "TARMAC",
    "Tarmac Grey": "TARMACGRY",
    "Tarmac Grey Heather": "TARMACGRYHTHR",
    "Teal": "TEAL",
    "Teal Green": "TEALGRN",
    "Teal Throttle": "TEALTHROTTLE",
    "Team": "TEAM",
    "Team Navy Blue": "TEAMNVBLUE",
    "Tech Olive/Legend Earth": "TECHOLV/LEGDEARTH",
    "Tennessee": "TEN",
    "Terra Cotta": "TERRACOTTA",
    "Texas": "TX",
    "Three": "THREE",
    "Throttle": "THROTTLE",
    "Thunder": "THUNDER",
    "Tidal": "TIDAL",
    "Tidal Blue": "TIDALBLUE",
    "Tint": "TINT",
    "Titanium": "TITN",
    "Titanium Gray": "TITNGRY",
    "TNF": "TNF",
    "TNF Black": "TNFBLK",
    "TNF Black Heather": "TNFBLKHTHR",
    "TNF Blackberry Wine": "TNFBLKBERRYWINE",
    "TNF Dark Grey Heather": "TNFDRKGRYHTHR",
    "TNF Dark Grey Heather/Cardinal Red": "TNFDRKGRYHTHR/CRDNLRED",
    "TNF Medium Grey Heather": "TNFMGRYHTHR",
    "Toddler": "T",
    "Tour": "TOUR",
    "Tour Blue": "TOURBLUE",
    "Tour Blue Heather": "TOURBLUEHTHR",
    "Trails": "TRAILS",
    "Translucent": "TRNSL",
    "Translucent Blue": "TRNSLBLUE",
    "Translucent Clear": "TRNSLCLEAR",
    "Translucent Green": "TRNSLGRN",
    "Triblend": "TRIBLD",
    "True Blue": "TRUEBLUE",
    "True Navy": "TRUENV",
    "True Navy Heather": "TRUENVHTHR",
    "True Navy Heather ": "TRUENVHTHR",
    "True Navy Heather/True Navy": "TRUENVHTHR/TRUENV",
    "True Navy/Gold": "TRUENV/GOLD",
    "True Navy/Grey": "TRUENV/GRY",
    "True Navy/Reflective": "TRUENV/RFV",
    "True Navy/White": "TRUENV/WHT",
    "True Navy/White/True Navy": "TRUENV/WHT/TRUENV",
    "True Pink/White": "TRUEPINK/WHT",
    "True Red": "TRUERED",
    "True Red/White": "TRUERED/WHT",
    "True Royal": "TRUERYL",
    "True Royal Heather": "TRUERYLHTHR",
    "True Royal/True Black": "TRUERYL/TRUEBLK",
    "True Royal/White": "TRUERYL/WHT",
    "Turquoise": "TRQ",
    "Turquoise Plaid": "TQRPLAID",
    "Twill": "TWILL",
    "Typhon": "TYPHON",
    "Typhon/Black": "TYPHON/BLK",
    "Ultra Silver Grey": "ULTRASLVRGRY",
    "Ultramarine Blue": "ULTRAMRNBLUE",
    "University": "UNIV",
    "University Red": "UNIVRED",
    "Unscented": "UNSCENTED",
    "Urban": "URBAN",
    "Urban Navy Heather": "URBANNVHTHR",
    "Valor": "VALOR",
    "Valor Blue": "VALORBLUE",
    "Vanilla": "VANILLA",
    "Varsity": "VARSITY",
    "Vibrant": "VIBRANT",
    "Vibrant Green": "VIBRANTGRN",
    "Vintage": "VNTG",
    "Vintage Heather/Vintage Heather": "VNTGHTHR/VNTGHTHR",
    "Vintage Hot Pink/Blended White": "VNTGHOTPINK/BLNDWHT",
    "Vintage Hot Pink/White": "VNTGHOTPINK/WHT",
    "Vintage Indigo Heather": "VNTGINDIGOHTHR",
    "Vintage Indigo/Black": "VNTGINDIGO/BLK",
    "Vintage Navy": "VNTGNV",
    "Vintage Navy/White": "VNTGNV/WHT",
    "Vintage Royal/Blended White": "VNTGRYL/BLENDEDWHT",
    "Vintage Royal/White": "VNTGRYL/WHT",
    "Vintage Smoke/Blended White": "VNTGSMK/BLNDWHT",
    "Vintage Smoke/White": "VNTGSMK/WHT",
    "Vivid": "VIVID",
    "Vivid Blue": "VIVIDBLUE",
    "Vivid Pink": "VIVIDPINK",
    "Void": "VOID",
    "Volcanic Ash": "VOLCANICASH",
    "Volt": "VOLT",
    "Voltage": "VTG",
    "Wahoo": "WAHOO",
    "Waist x Length": "WAISTLENGTH",
    "Walnut": "WALNUT",
    "Wasabe": "WASABE",
    "Wasabi": "WASABI",
    "Wash": "WSH",
    "Washed": "WSHD",
    "Watermelon": "WMLN",
    "Wheat": "WHEAT",
    "White": "WHT",
    "White & Blue Stripe": "WHTBLUESTRP",
    "White & Grey": "WHT/GRY",
    "White Blue": "WHTBLUE",
    "White Brown": "WHTBROWN",
    "White Orange": "WHTORNG",
    "White Plaid": "WHTPLAID",
    "White Powder": "WHTPOWDER",
    "White Solid/Black": "WHTSOLID/BLK",
    "White Triad Solid": "WHTTRIADSOLID",
    "White with Black Rope": "WHT/BLK",
    "White/Aluminum/Navy": "WHT/ALUM/NV",
    "White/Black": "WHT/BLK",
    "White/Carbon": "WHT/CARBON",
    "White/Grey": "WHT/GRY",
    "White/Light Stone": "WHT/LTSTN",
    "White/Mid Grey": "WHT/MDGRY",
    "White/Navy": "WHT/NV",
    "White/Royal": "WHT/RYL",
    "Wht/Md Gry": "WHT/MDGRY",
    "Windsor Grey Heather": "WINDSORGRYHTHR",
    "Wine": "WINE",
    "Winter White": "WINTERWHT",
    "Wolf": "WOLF",
    "Wood": "WOOD",
    "Wood/Black/Stainless Steel": "WOOD/BLK/STAINLESSSTL",
    "Xtra": "XTRA",
    "Yellow": "YLW",
    "Yellow/Black": "YLW/BLK",
    "Yellow/Black": "YLW/WHT",
    "Zinc Grey": "ZINCGRY",
    "Grey Three/ Team Royal/ Navy": "GY3/TR/NVY",
    "Burnt Red/Charcoal": "BRD/CHR",
    "Burgundy/Light Stone": "BUR/LTSTN",
    "Mediterranean Blue": "MBL",
    "Real Red": "REALRED",
    "Realtree Xtra/Charcoal": "RTX/CHR",
    "Red/Charcoal": "RED/CHR",
    "Team Power Red": "TPRED",
    "Grey-Black/Electric Black": "GYB/EBK",
    "Navy Frost": "NVFROST",
    "Mid Grey Melange": "MDGRYMLNG",
    "Bluish Grey": "BLSHGRY",
    "White-Black": "WH-BLK",
    "Green Camo/White": "GRCAMO/WH",
    "Graphite/Black/Graphite": "GRPH/BLK/GRPH",
    "Realtree Edge/ Brown": "REALEDGE/BR",
    "White/Black/White": "WH/BLK/WH",
    "Denim/Khaki": "DENIM/KH",
    "Buffalo Plaid": "BUFFALO/PL",
    "Greenstone": "GRSTN",
    "Camopink": "CAMOPNK",
    "Brown/Silver": "BR/SLVR",
    "Rescue Red": "RESCRED",
    "White/RedStar": "WH/REDSTR",
    "BLUEJEAN": "BLUEJEAN",
    "COYOTETAN": "COYOTETAN",
    "CTBROWN": "CTBROWN",
    "Smoke Blue/Beige/Smoke Blue": "SMBLUE/BEIGE/SMBLUE",
    "Silver/White/Silver": "SLVR/WH/SLVR",
    "Dark Green/White/Dark Green": "DARKGR/WH/DARKGR",
    "Red/White/Red": "RED/WH/RED",
    "Custom": "CUSTOM",
    "Emerald Tri Blend": "EMETRIBLEND",
    "Smoke Grey": "SMKGRY",
    "Pure White": "PUREWH",
    "Natural Heather": "NATURALHTHR",
    "Moss": "MOSS",
    "Flag Red ": "FLAGRED",
    "Skyscraper Grey": "SKYSCRPRGRY",
    "Lite Grey": "LTGRY",
    "Jet Blue": "JETBLUE",
    "Platinum Grey": "PLTNMGRY",
    "Navy/Ash": "NV/ASH",
    "Dark Heather": "DKRHTHR",
    "Grey-Black Electric/Black": "GRBLKELEC/BLK",
    "Lakeshore": "LAKESHORE",
    "Basil Heather": "BASILHTHR",
    "Lucky Blue Melange": "LBMLNG",
    "Green Oxide": "GROXIDE",
    "Vintage Red/ White": "VNTGRED/WH"
  };

  const map = Object.fromEntries(
    Object.entries(rawMap).map(([k, v]) => [k.toLowerCase(), v])
  );

  return map[color?.toLowerCase?.()] || null;
}