export function getPlacementCode(placement) {
    const rawMap = {
        "Left Right": "LR",
        "Back Yoke": "BY",
        "Bag Front/Front Pocket": "BFP",
        "Bag Side Pocket": "BSP",
        "Beanie Back": "BB",
        "Beanie Front": "BF",
        "Blanket/Towel - Corner": "BTC",
        "Blanket/Towel - Corner at an Angle": "BTCA",
        "Blanket/Towel Bottom Centered as item is rolled": "BTBC",
        "Cap Back": "CB",
        "Cap Front": "CF",
        "Cap Front + Left & Right Wearer Side Logos": "CF270",
        "Cap Front + Left Wearer's Side Logo": "CFL90",
        "Cap Front + Right Wearer's Side Logo": "CFR90",
        "Cap Left Wearer's Panel": "CLP",
        "Cap Left Wearer's Panel + Left & Right Wearer Side Logos": "CLP270",
        "Cap Left Wearer's Panel + Left Wearer's Side Logo": "CLPL90",
        "Cap Left Wearer's Panel + Right Wearer's Side Logo": "CLPR90",
        "Cap Right Wearer's Panel": "CRP",
        "Cap Right Wearer's Panel + Left & Right Wearer Side Logos": "CRP270",
        "Cap Right Wearer's Panel + Left Wearer's Side Logo": "CRPL90",
        "Cap Right Wearer's Panel + Right Wearer's Side Logo": "CRPR90",
        "Chair Back": "CHRB",
        "Cuff Left Sleeve": "CLS",
        "Cuff Right Sleeve": "CRS",
        "Front Center": "FRC",
        "Front Hat": "FH",
        "Front Vertical": "FRV",
        "Full Back": "FB",
        "Full Chest": "FC",
        "Full Coverage": "FULL",
        "Left Chest": "LC",
        "Left Chest / Back Yoke": "LCBY",
        "Left Chest Above Pocket": "LCAP",
        "Left Chest/Full Back": "LC&FB",
        "Left Chest/Right Sleeve": "LC&RS",
        "Left Vertical Sleeve Print": "LVS",
        "Left Wearer Hip": "LWH",
        "Left Wearer's Leg Near Hem": "LWLH",
        "Left Wearer's Sleeve": "LS",
        "Pocket Imprint": "PI",
        "Polo Collar - Left Side": "CL",
        "Polo Collar - Right Side": "CR",
        "Promo Bottom Center": "PBC",
        "Promo Bottom Left Center": "PBLC",
        "Promo Center": "PC",
        "Promo Deboss": "PD",
        "Promo Flap Center": "PFLP",
        "Promo Front Panel Center": "PFPC",
        "Promo Front Pocket": "PFP",
        "Promo Left": "PL",
        "Promo Max": "PM",
        "Promo Patch": "PPA",
        "Promo Plate": "PPL",
        "Promo Right": "PR",
        "Promo Standard": "PS",
        "Promo Top Center": "PTC",
        "Promo Upper Panel Center": "PUPC",
        "Promo Vertical": "PV",
        "Promo Wrap": "PW",
        "Rear Hat": "RH",
        "Right Chest": "RC",
        "Right Vertical Sleeve Print": "RVS",
        "Right Wearer Hip": "RWH",
        "Right Wearer's Leg Near Hem": "RWLH",
        "Right Wearer's Sleeve": "RS",
        "Step & Repeat": "S&R",
        "Top Center": "TC",
        "Full Chest / Full Back": "FCFB",
        "Promo Standard|Promo Top Center": "PS|PTC",
        "Bag Front": "BF"
    };

    const map = Object.fromEntries(
        Object.entries(rawMap).map(([k, v]) => [k.toLowerCase(), v])
    );

    return map[placement?.toLowerCase?.()] || null;
}