import { ColorModeButton } from "@/components/ui/color-mode";
import { Container, Stack, Field, Flex, Card, Input, Button, SimpleGrid, Text, HStack, Separator, Table, Heading, Textarea, Box } from "@chakra-ui/react";
import Head from "next/head";
import { useState, useRef, useEffect } from "react";
import { LuPlus } from "react-icons/lu";
import { PiFileCsvLight } from "react-icons/pi";
import { TbTableExport } from "react-icons/tb";

const initialForm = {
  vendor_link: "",
  vendor_name: "",
  product_name: "",
  product_sku: "",
  product_color: "",
  product_sizes_offered: "",
  product_family: "",
  inhouse_vendor_decorated: "",
  standard_decoration_method: "",
  standard_decoration_placement: "",
  standard_number_imprint_colors: "",
  vendor_minimum_order_qty: "",
  vendor_end_qty: "",
  vendor_product_price: "",
  product_brand: "",
  vendor_sizechart_link: "",
  product_html_specifications: "",
  available_images: "",
}



export default function Home() {
  const [form, setForm] = useState(initialForm);
  const [products, setProducts] = useState([])
  const debounceTimer = useRef(null);

  const stripAttributes = (html) => {
    if (!html) return "";

    let cleaned = html

      .replace(/<(script|style|link|meta|iframe|object|embed|noscript)[\s\S]*?<\/\1>/gi, "")
      .replace(/<(script|style|link|meta|iframe|object|embed|noscript)[^>]*>/gi, "")

      .replace(/<(\w+)([^>]*)>/g, "<$1>")

      .replace(/>\s+</g, "><")

      .replace(/[\u200E\u200F\u202A-\u202E]/g, "")

      .replace(/&quot;/g, "");

    return cleaned.trim();
  };



  const handleChange = (e) => {
    const { name, value } = e.target;
    setForm((prev) => ({
      ...prev,
      [name]: value,
    }));
    clearTimeout(debounceTimer.current);
    debounceTimer.current = setTimeout(() => {
      setForm((prev) => ({
        ...prev,
        [name]: value,
      }));
    }, 300);
  };

  // useEffect(() => {
  //   const handleKey = (e) => {
  //     if (e.shiftKey && e.code === "Space") {
  //       handleSubmit()
  //     }
  //   };

  //   window.addEventListener("keydown", handleKey);
  //   return () => window.removeEventListener("keydown", handleKey);
  // }, []);

  const handleSubmit = (e) => {
    if (e) e.preventDefault(); // only prevent if event exists

    if (
      !form.vendor_link.trim() ||
      !form.vendor_name.trim() ||
      !form.product_name.trim()
    ) {
      alert("Vendor Link, Vendor Name, and Product Name are required.");
      return;
    }

    const isDuplicate = products.some(
      (p) => p.vendor_link.trim().toLowerCase() === form.vendor_link.trim().toLowerCase()
    );

    if (isDuplicate) {
      alert("Vendor link already exists. Please use a unique one.");
      return;
    }

    setProducts([...products, form]);
    setForm(initialForm);
  };

  const handleExport = async () => {
    const cleaned = products.map((p) => ({
      ...p,
      product_html_specifications: stripAttributes(p.product_html_specifications || "")
    }));

    const res = await fetch("/api/export", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ data: cleaned })
    });

    const blob = await res.blob();
    const url = window.URL.createObjectURL(blob);

    const a = document.createElement("a");
    a.href = url;
    a.download = "export_" + Date.now() + ".csv";
    a.click();

    window.URL.revokeObjectURL(url);
  }

  return (
    <>
      <Head>
        <title>Product Data Enrichment Form</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Stack px={0} h="100vh" overflow="hidden" gap={0}>
        <Flex h="6dvh" p={4} alignItems="center" justifyContent="space-between">
          <Heading>Product Data Enrichment Processor</Heading>
          <ColorModeButton />
        </Flex>
        <Flex flex={1} p={4} bg="bg.muted">
          <Stack gap={2} w="30%" bg="bg" p={4}>
            <HStack gap={4}>
              <Field.Root>
                <Field.Label>Vendor Link</Field.Label>
                <Input size="sm" type="text" name="vendor_link" value={form.vendor_link} onChange={handleChange} />
              </Field.Root>
              <Field.Root>
                <Field.Label>Vendor Name</Field.Label>
                <Input size="sm" type="text" name="vendor_name" value={form.vendor_name} onChange={handleChange} />
              </Field.Root>
            </HStack>
            <HStack gap={4}>
              <Field.Root>
                <Field.Label>Product Name</Field.Label>
                <Input size="sm" type="text" name="product_name" value={form.product_name} onChange={handleChange} />
              </Field.Root>
              <Field.Root>
                <Field.Label>Product SKU</Field.Label>
                <Input size="sm" type="text" name="product_sku" value={form.product_sku} onChange={handleChange} />
              </Field.Root>
            </HStack>
            <HStack gap={4}>
              <Field.Root>
                <Field.Label>Product Color</Field.Label>
                <Input size="sm" type="text" name="product_color" value={form.product_color} onChange={handleChange} />
              </Field.Root>
              <Field.Root>
                <Field.Label>Product Sizes Offered</Field.Label>
                <Input size="sm" type="text" name="product_sizes_offered" value={form.product_sizes_offered} onChange={handleChange} />
              </Field.Root>
            </HStack>
            <HStack gap={4}>
              <Field.Root>
                <Field.Label>Product Family</Field.Label>
                <Input size="sm" type="text" name="product_family" value={form.product_family} onChange={handleChange} />
              </Field.Root>
              <Field.Root>
                <Field.Label>In-House Vendor Decorated</Field.Label>
                <Input size="sm" type="text" name="inhouse_vendor_decorated" value={form.inhouse_vendor_decorated} onChange={handleChange} />
              </Field.Root>
            </HStack>
            <HStack gap={4}>
              <Field.Root>
                <Field.Label>Decoration Method</Field.Label>
                <Input size="sm" type="text" name="standard_decoration_method" value={form.standard_decoration_method} onChange={handleChange} />
              </Field.Root>
              <Field.Root>
                <Field.Label>Decoration Placement</Field.Label>
                <Input size="sm" type="text" name="standard_decoration_placement" value={form.standard_decoration_placement} onChange={handleChange} />
              </Field.Root>
              <Field.Root>
                <Field.Label># of Imprint Colors</Field.Label>
                <Input size="sm" type="text" name="standard_number_imprint_colors" value={form.standard_number_imprint_colors} onChange={handleChange} />
              </Field.Root>
            </HStack>
            <HStack gap={4}>
              <Field.Root>
                <Field.Label>Min Order QTY</Field.Label>
                <Input size="sm" type="text" name="vendor_minimum_order_qty" value={form.vendor_minimum_order_qty} onChange={handleChange} />
              </Field.Root>
              <Field.Root>
                <Field.Label>End Quantity</Field.Label>
                <Input size="sm" type="text" name="vendor_end_qty" value={form.vendor_end_qty} onChange={handleChange} />
              </Field.Root>
              <Field.Root>
                <Field.Label>Vendor Product Price</Field.Label>
                <Input size="sm" type="text" name="vendor_product_price" value={form.vendor_product_price} onChange={handleChange} />
              </Field.Root>
            </HStack>
            <HStack gap={4}>
              <Field.Root>
                <Field.Label>Product Brand</Field.Label>
                <Input size="sm" type="text" name="product_brand" value={form.product_brand} onChange={handleChange} />
              </Field.Root>
              <Field.Root>
                <Field.Label>Vendor Size Chart Link</Field.Label>
                <Input size="sm" type="text" name="vendor_sizechart_link" value={form.vendor_sizechart_link} onChange={handleChange} />
              </Field.Root>
            </HStack>
            <Field.Root>
              <Field.Label>Available Images</Field.Label>
              <Input size="sm" type="text" name="available_images" value={form.available_images} onChange={handleChange} />
            </Field.Root>
            <Field.Root>
              <Field.Label>Product HTML Specifications</Field.Label>
              <Textarea size="sm" name="product_html_specifications" value={form.product_html_specifications} onChange={handleChange} />
              <Text>Preview</Text>
              <Text lineClamp={2}>{stripAttributes(form.product_html_specifications)}</Text>
            </Field.Root>
            <Button rounded="full" mt="auto" onClick={handleSubmit}>Submit (or Shift + Space)</Button>
          </Stack>
          <Box
            flex={1}
            overflow="auto"
          >
            <Table.Root size="sm" striped interactive>
              <Table.Header>
                <Table.Row>
                  <Table.ColumnHeader>Vendor Link</Table.ColumnHeader>
                  <Table.ColumnHeader>Vendor Name</Table.ColumnHeader>
                  <Table.ColumnHeader>Product Name</Table.ColumnHeader>
                  <Table.ColumnHeader>SKU</Table.ColumnHeader>
                </Table.Row>
              </Table.Header>
              <Table.Body>
                {products.length === 0 ? (
                  <Table.Row>
                    <Table.Cell colSpan={3}>No products. Add</Table.Cell>
                  </Table.Row>
                ) :
                  products.map((product) => (
                    <Table.Row key={product.vendor_link}>
                      <Table.Cell><Text truncate maxW="240px">{product.vendor_link}</Text></Table.Cell>
                      <Table.Cell><Text truncate maxW="120px">{product.vendor_name}</Text></Table.Cell>
                      <Table.Cell><Text truncate maxW="400px">{product.product_name}</Text></Table.Cell>
                      <Table.Cell><Text truncate maxW="400px">{product.product_sku}</Text></Table.Cell>
                    </Table.Row>
                  ))
                }
              </Table.Body>
            </Table.Root>
          </Box>
        </Flex >
        <Flex
          borderTop="1px solid"
          borderColor="bg.muted"
          bg="bg"
          p={4}
          justifyContent="flex-end"
        >
          <Button onClick={handleExport} disabled={products.length === 0}>Create CSV <TbTableExport /></Button>
        </Flex>
      </Stack>
    </>
  );
}
